services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: demucs_production

  web:
    build: ./web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      DB_HOST: db
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DEMUCS_USE_VOLUMES: "true"
      DEMUCS_INPUT_VOLUME: demucs_input
      DEMUCS_OUTPUT_VOLUME: demucs_output
      DEMUCS_MODELS_VOLUME: demucs_models
      DEMUCS_INPUT_PATH: /data/input
      DEMUCS_OUTPUT_PATH: /data/output
      DEMUCS_MODELS_PATH: /data/models
      SOLID_QUEUE_IN_PUMA: "false"
      AWS_ACCESS_KEY_ID:     ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION:            ${AWS_REGION}
      AWS_BUCKET:            ${AWS_BUCKET}
      HTTP_READ_TIMEOUT: "300"
      HTTP_WRITE_TIMEOUT: "300"
      STORAGE_PATH: /data/thruster
      TLS_DOMAIN: ${TLS_DOMAIN}
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - input:/data/input
      - output:/data/output
      - models:/data/models
      - thruster:/data/thruster

  worker:
    build: ./web
    restart: always
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      DB_HOST: db
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DEMUCS_USE_VOLUMES: "true"
      DEMUCS_INPUT_VOLUME: demucs_input
      DEMUCS_OUTPUT_VOLUME: demucs_output
      DEMUCS_MODELS_VOLUME: demucs_models
      DEMUCS_INPUT_PATH: /data/input
      DEMUCS_OUTPUT_PATH: /data/output
      DEMUCS_MODELS_PATH: /data/models
      AWS_ACCESS_KEY_ID:     ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION:            ${AWS_REGION}
      AWS_BUCKET:            ${AWS_BUCKET}
    command: ["./bin/jobs"]
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - input:/data/input
      - output:/data/output
      - models:/data/models

volumes:
  pgdata:
  input:
    name: demucs_input
  output:
    name: demucs_output
  models:
    name: demucs_models
  thruster:
