apiVersion: apps/v1
kind: Deployment
metadata:
  name: demucs
  namespace: demucs
spec:
  template:
    spec:
      containers:
        - name: demucs
          env:
            - name: DEMUCS_DEVICE
              value: cuda
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              nvidia.com/gpu: "1"
