apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - postgres.yaml
  - minio.yaml
  - minio-init.yaml
  - web.yaml
  - worker.yaml
  - demucs.yaml
  - postfix.yaml
