apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: demucs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      initContainers:
        - name: dkim-init
          image: busybox
          command:
            - sh
            - -c
            - |
              cp /run/dkim-secret/dkim.private "/etc/opendkim/keys/www.demucsr.com,demucsr.com.private"
              chmod 600 "/etc/opendkim/keys/www.demucsr.com,demucsr.com.private"
              chown 101:104 "/etc/opendkim/keys/www.demucsr.com,demucsr.com.private"
          volumeMounts:
            - name: dkim-secret
              mountPath: /run/dkim-secret/dkim.private
              subPath: dkim.private
            - name: dkim-keys
              mountPath: /etc/opendkim/keys
      containers:
        - name: postfix
          image: boky/postfix
          env:
            - name: ALLOWED_SENDER_DOMAINS
              valueFrom:
                secretKeyRef:
                  name: demucs-secrets
                  key: TLS_DOMAIN
            - name: HOSTNAME
              value: mail.demucsr.com
            - name: DKIM_AUTOGENERATE
              value: "true"
          volumeMounts:
            - name: dkim-keys
              mountPath: /etc/opendkim/keys
      volumes:
        - name: dkim-secret
          secret:
            secretName: postfix-dkim
            defaultMode: 0400
        - name: dkim-keys
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postfix
  namespace: demucs
spec:
  selector:
    app: postfix
  ports:
    - port: 25
      targetPort: 25
  type: ClusterIP
