apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s

patches:
  - path: patches/demucs-gpu.yaml
  - path: patches/web-no-tls.yaml
  - path: patches/worker-local.yaml
